/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:musicURL:765278:
  loop();
  println("musicURL - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:musicURL:765278:

public void PlayPress(GButton source, GEvent event) { //_CODE_:Play:880241:
  loop();
  if(!playFlag)
     player=minim.loadFile(musicURL.getText(),width);
  println("Play - GButton >> GEvent." + event + " @ " + millis());
  player.play();
  playFlag=true;
  offlength=player.length()/380;
} //_CODE_:Play:880241:

public void LoadPress(GButton source, GEvent event) { //_CODE_:Load:462780:
  loop();
  od.setVisible(true);
  musicURL.setText(od.getDirectory()+od.getFile());
  println("Load - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Load:462780:

public void StopPress(GButton source, GEvent event) { //_CODE_:Stop:569152:
  loop();
  println("Stop - GButton >> GEvent." + event + " @ " + millis());
  player.close();
  playFlag=false;
} //_CODE_:Stop:569152:

public void PausePress(GButton source, GEvent event) { //_CODE_:Pause:435662:
  println("Pause - GButton >> GEvent." + event + " @ " + millis());
  player.pause();
  noLoop();
} //_CODE_:Pause:435662:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(true);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  musicURL = new GTextField(this, 10, 220, 290, 30, G4P.SCROLLBARS_NONE);
  musicURL.setOpaque(true);
  musicURL.addEventHandler(this, "textfield1_change1");
  Play = new GButton(this, 10, 260, 80, 30);
  Play.setText("Play");
  Play.addEventHandler(this, "PlayPress");
  Load = new GButton(this, 310, 220, 80, 30);
  Load.setText("Load");
  Load.addEventHandler(this, "LoadPress");
  Stop = new GButton(this, 310, 260, 80, 30);
  Stop.setText("Stop");
  Stop.addEventHandler(this, "StopPress");
  Pause = new GButton(this, 160, 260, 80, 30);
  Pause.setText("Pause");
  Pause.addEventHandler(this, "PausePress");
}

// Variable declarations 
// autogenerated do not edit
GTextField musicURL; 
GButton Play; 
GButton Load; 
GButton Stop; 
GButton Pause; 
FileDialog od=new FileDialog(new Frame(),"Open",FileDialog.LOAD);
